//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Digi.XBee.Internal.Protocol
{
    
    
    /// <summary>
    /// Class to implement the XBee Enumeration <b>ModemStatus</b>
    /// </summary>
    public enum ModemStatus
    {
        
        /// <summary>
        /// Default unknown value
        /// </summary>
        UNKNOWN = -1,
        
        /// <summary>
        ///  [0] 
        /// </summary>
        HARDWARE_RESET = 0x0000,
        
        /// <summary>
        ///  [1] 
        /// </summary>
        WATCHDOG_TIMER_RESET = 0x0001,
        
        /// <summary>
        ///  [2] 
        /// </summary>
        JOINED_NETWORK = 0x0002,
        
        /// <summary>
        ///  [3] 
        /// </summary>
        DISASSOCIATED = 0x0003,
        
        /// <summary>
        ///  [6] 
        /// </summary>
        COORDINATOR_STARTED = 0x0006,
        
        /// <summary>
        ///  [7] 
        /// </summary>
        NETWORK_SECURITY_KEY_UPDATED = 0x0007,
        
        /// <summary>
        ///  [13] 
        /// </summary>
        VOLTAGE_SUPPLY_LIMIT_EXCEEDED = 0x000D,
        
        /// <summary>
        ///  [17] 
        /// </summary>
        MODEM_CONFIGURATION_CHANGED_WHILE_JOIN_IN_PROGRESS = 0x0011,
    }
}
