//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Digi.XBee.Internal.Protocol
{
    
    
    /// <summary>
    /// Class to implement the XBee command " Set Reset ".
    /// AT Command <b>RE</b></p>This command sets all parameters except ZS and KY to their default
    /// values. To change ZS and KY, you must explicitly set them. In order for the default parameters
    /// to persist through subsequent resets, send a separate WR command after RE. Read-only
    /// parameters are not directly affected by RE and reflect the current state of the device. 
    /// This class provides methods for processing XBee API commands.
    /// </summary>
    public class XBeeSetResetCommand : XBeeFrame, IXBeeCommand 
    {
        
        /// <summary>
        ///  </summary>
        private int _frameId;
        
        /// <summary>
        /// The frameId to set as </summary>
        /// <seecref="uint8"
        ///>
        ///  </see>
        public void SetFrameId(int frameId)
        {
            _frameId = frameId;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public int[] Serialize()
        {
            SerializeCommand(8);
            SerializeInt8(_frameId);
            SerializeAtCommand("RE");
            return GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder(289);
            builder.Append("XBeeSetResetCommand [frameId=");
            builder.Append(_frameId);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
