//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Digi.XBee.Internal.Protocol
{
    
    
    /// <summary>
    /// Class to implement the XBee command " Set ZigBee Stack Profile ".
    /// AT Command <b>ZS</b></p>Set or read the Zigbee stack profile value. This must be the same on
    /// all devices that will join the same network. Effective with release 4x5E, changing ZS to a
    /// different value causes all current parameters to be written to persistent storage. 
    /// This class provides methods for processing XBee API commands.
    /// </summary>
    public class XBeeSetZigbeeStackProfileCommand : XBeeFrame, IXBeeCommand 
    {
        
        /// <summary>
        ///  </summary>
        private int _frameId;
        
        /// <summary>
        ///  </summary>
        private int _stackProfile;
        
        /// <summary>
        /// The frameId to set as </summary>
        /// <seecref="uint8"
        ///>
        ///  </see>
        public void SetFrameId(int frameId)
        {
            this._frameId = frameId;
        }
        
        /// <summary>
        /// The stackProfile to set as </summary>
        /// <seecref="uint8"
        ///>
        ///  </see>
        public void SetStackProfile(int stackProfile)
        {
            this._stackProfile = stackProfile;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public int[] Serialize()
        {
            this.SerializeCommand(8);
            this.SerializeInt8(_frameId);
            this.SerializeAtCommand("ZS");
            this.SerializeInt8(_stackProfile);
            return this.GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder(392);
            builder.Append("XBeeSetZigbeeStackProfileCommand [frameId=");
            builder.Append(this._frameId);
            builder.Append(", stackProfile=");
            builder.Append(this._stackProfile);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
