//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Digi.XBee.Internal.Protocol
{
    
    
    /// <summary>
    /// Class to implement the XBee command " Join Notification ".
    /// AT Command <b>JN</b></p>Set or read the join notification setting. If enabled, the device
    /// transmits a broadcast node identification packet on power up and when joining. This action
    /// blinks the Associate LED rapidly on all devices that receive the transmission, and sends an
    /// API frame out the serial port of API devices. Digi recommends you disable this feature for
    /// large networks to prevent excessive broadcasts. 
    /// This class provides methods for processing XBee API commands.
    /// </summary>
    public class XBeeJoinNotificationResponse : XBeeFrame, IXBeeResponse 
    {
        
        /// <summary>
        /// Response field
        /// </summary>
        private int _frameId;
        
        /// <summary>
        /// Response field
        /// </summary>
        private CommandStatus _commandStatus;
        
        /// <summary>
        /// Response field
        /// </summary>
        private bool _enableNotification;
        
        /// <summary>
        ///  Return the frameId as <see cref="System.Int32"/>
        /// </summary>
        public int GetFrameId()
        {
            return _frameId;
        }
        
        /// <summary>
        ///  Return the commandStatus as <see cref="CommandStatus"/>
        /// </summary>
        public CommandStatus GetCommandStatus()
        {
            return _commandStatus;
        }
        
        /// <summary>
        ///  Return the enableNotification as <see cref="System.Boolean"/>
        /// </summary>
        public bool GetEnableNotification()
        {
            return _enableNotification;
        }
        
        /// <summary>
        /// Method for deserializing the fields for the response </summary>
        public void Deserialize(int[] incomingData)
        {
            InitializeDeserializer(incomingData);
            _frameId = DeserializeInt8();
            DeserializeAtCommand();
            _commandStatus = DeserializeCommandStatus();
            if (_commandStatus != CommandStatus.OK || IsComplete())
            {
                    return;
            }
            _enableNotification = DeserializeBoolean();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder(478);
            builder.Append("XBeeJoinNotificationResponse [frameId=");
            builder.Append(_frameId);
            builder.Append(", commandStatus=");
            builder.Append(_commandStatus);
            builder.Append(_enableNotification);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
