// License text here

using System;
using System.Collections.Generic;
using System.Text;

/**
 * Enumeration of IASACE attribute Arm Mode options.
 *
 * Code is auto-generated. Modifications may be overwritten!
 *
 */

/* Autogenerated: 14.02.2019 - 18:41 */
namespace ZigBeeNet.ZCL.Clusters.IASACE
{
   public enum ArmMode
   {
       DISARM = 0x0000,
       ARM_DAY = 0x0001,
       ARM_NIGHT = 0x0002,
       ARM_ALL_ZONES = 0x0003
   }
}
