using System;
using System.Text;
using ZigBeeNet.Transaction;
using ZigBeeNet.ZCL;
using ZigBeeNet.ZCL.Protocol;

namespace ZigBeeNet.ZDO.Command
{
    /// <summary>
    /// Find Node Cache Request value object class.
    /// 
    /// The Find_node_cache_req is provided to enable ZigBee devices on the network to
    /// broadcast to all devices for which macRxOnWhenIdle = TRUE a request to find a
    /// device on the network that holds discovery information for the device of interest,
    /// as specified in the request parameters. The effect of a successful
    /// Find_node_cache_req is to have the Primary Discovery Cache device, holding
    /// discovery information for the device of interest, unicast a Find_node_cache_rsp
    /// back to the Local Device. Note that, like the NWK_addr_req, only the device
    /// meeting this criteria shall respond to the request generated by
    /// Find_node_cache_req.
    /// 
    /// </summary>
    public class FindNodeCacheRequest : ZdoRequest
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        public FindNodeCacheRequest()
        {
            ClusterId = 0x001C;
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();

            builder.Append("FindNodeCacheRequest [")
                   .Append(base.ToString())
                   .Append(']');

            return builder.ToString();
        }

    }
}
