using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZigBeeNet.ZCL;
using ZigBeeNet.ZCL.Protocol;
using ZigBeeNet.ZDO.Field;


namespace ZigBeeNet.ZDO.Command
{
    /// <summary>
    /// User Descriptor Response value object class.
    ///
    ///
    /// The User_Desc_rsp is generated by a remote device in response to a User_Desc_req
    /// directed to the remote device. This command shall be unicast to the originator of the
    /// User_Desc_req command.
    ///
    /// Code is auto-generated. Modifications may be overwritten!
    /// </summary>
    public class UserDescriptorResponse : ZdoResponse
    {
        /// <summary>
        /// The ZDO cluster ID.
        /// </summary>
        public const ushort CLUSTER_ID = 0x8011;

        /// <summary>
        /// NWK Addr Of Interest command message field.
        /// </summary>
        public ushort NwkAddrOfInterest { get; set; }

        /// <summary>
        /// Length command message field.
        /// </summary>
        public byte Length { get; set; }

        /// <summary>
        /// User Descriptor command message field.
        /// </summary>
        public UserDescriptor UserDescriptor { get; set; }

        /// <summary>
        /// Default constructor.
        /// </summary>
        public UserDescriptorResponse()
        {
            ClusterId = CLUSTER_ID;
        }

        internal override void Serialize(ZclFieldSerializer serializer)
        {
            base.Serialize(serializer);

            serializer.Serialize(Status, ZclDataType.Get(DataType.ZDO_STATUS));
            serializer.Serialize(NwkAddrOfInterest, ZclDataType.Get(DataType.NWK_ADDRESS));
            serializer.Serialize(Length, ZclDataType.Get(DataType.UNSIGNED_8_BIT_INTEGER));
            serializer.Serialize(UserDescriptor, ZclDataType.Get(DataType.USER_DESCRIPTOR));
        }

        internal override void Deserialize(ZclFieldDeserializer deserializer)
        {
            base.Deserialize(deserializer);

            Status = deserializer.Deserialize<ZdoStatus>(ZclDataType.Get(DataType.ZDO_STATUS));
            if (Status != ZdoStatus.SUCCESS)
            {
                // Don't read the full response if we have an error
                return;
            }
            NwkAddrOfInterest = deserializer.Deserialize<ushort>(ZclDataType.Get(DataType.NWK_ADDRESS));
            Length = deserializer.Deserialize<byte>(ZclDataType.Get(DataType.UNSIGNED_8_BIT_INTEGER));
            UserDescriptor = deserializer.Deserialize<UserDescriptor>(ZclDataType.Get(DataType.USER_DESCRIPTOR));
        }

        public override string ToString()
        {
            var builder = new StringBuilder();

            builder.Append("UserDescriptorResponse [");
            builder.Append(base.ToString());
            builder.Append(", Status=");
            builder.Append(Status);
            builder.Append(", NwkAddrOfInterest=");
            builder.Append(NwkAddrOfInterest);
            builder.Append(", Length=");
            builder.Append(Length);
            builder.Append(", UserDescriptor=");
            builder.Append(UserDescriptor);
            builder.Append(']');

            return builder.ToString();
        }
    }
}
