//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Digi.XBee.Internal.Protocol
{
    
    
    /// <summary>
    /// Class to implement the XBee command " Get Ieee Address High ".
    /// AT Command <b>SH</b></p>Displays the upper 32 bits of the unique IEEE 64-bit extended
    /// address assigned to the XBee in the factory. 
    /// This class provides methods for processing XBee API commands.
    /// </summary>
    public class XBeeGetIeeeAddressHighCommand : XBeeFrame, IXBeeCommand 
    {
        
        /// <summary>
        ///  </summary>
        private int _frameId;
        
        /// <summary>
        /// The frameId to set as </summary>
        /// <seecref="uint8"
        ///>
        ///  </see>
        public void SetFrameId(int frameId)
        {
            _frameId = frameId;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public int[] Serialize()
        {
            SerializeCommand(8);
            SerializeInt8(_frameId);
            SerializeAtCommand("SH");
            return GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder(299);
            builder.Append("XBeeGetIeeeAddressHighCommand [frameId=");
            builder.Append(_frameId);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
