//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Structure
{
    
    
    /// <summary>
    /// Class to implement the Ember Enumeration <b>EmberGpProxyTableEntryStatus</b>
    ///<p>
    /// GP proxy table entry status.
    ///</p> </summary>
    public enum EmberGpProxyTableEntryStatus
    {
        
        /// <summary>
        /// Default unknown value
        /// </summary>
        UNKNOWN = -1,
        
        /// <summary>
        ///  [1] The GP table entry is in use for a Proxy Table Entry.
        /// </summary>
        EMBER_GP_PROXY_TABLE_ENTRY_STATUS_ACTIVE = 0x0001,
        
        /// <summary>
        ///  [255] The proxy table entry is not in use.
        /// </summary>
        EMBER_GP_PROXY_TABLE_ENTRY_STATUS_UNUSED = 0x00FF,
    }
}
