//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Structure
{
    
    
    /// <summary>
    /// Class to implement the Ember Enumeration <b>EmberZdoConfigurationFlags</b>
    ///<p>
    /// This is a bitmask that controls which incoming ZDO request messages are passed to the
    /// application.
    ///</p> </summary>
    public enum EmberZdoConfigurationFlags
    {
        
        /// <summary>
        /// Default unknown value
        /// </summary>
        UNKNOWN = -1,
        
        /// <summary>
        ///  [1] Set this flag in order to receive supported ZDO request messages via the
        /// incomingMessageHandler callback. A supported ZDO request is one that is handled by the
        /// EmberZNet stack. The stack will continue to handle the request and send the appropriate ZDO
        /// response even if this configuration option is enabled.
        /// </summary>
        EMBER_APP_RECEIVES_SUPPORTED_ZDO_REQUESTS = 0x0001,
        
        /// <summary>
        ///  [2] Set this flag in order to receive unsupported ZDO request messages via the
        /// incomingMessageHandler callback. An unsupported ZDO request is one that is not handled by
        /// the EmberZNet stack, other than to send a 'not supported' ZDO response. If this
        /// configuration option is enabled, the stack will no longer send any ZDO response, and it is the
        /// application's responsibility to do so.
        /// </summary>
        EMBER_APP_HANDLES_UNSUPPORTED_ZDO_REQUESTS = 0x0002,
        
        /// <summary>
        ///  [4] Set this flag in order to receive the following ZDO request messages via the
        /// incomingMessageHandler callback: SIMPLE_DESCRIPTOR_REQUEST,
        /// MATCH_DESCRIPTORS_REQUEST, and ACTIVE_ENDPOINTS_REQUEST. If this configuration
        /// option is enabled, the stack will no longer send any ZDO response for these requests, and it is
        /// the application's responsibility to do so.
        /// </summary>
        EMBER_APP_HANDLES_ZDO_ENDPOINT_REQUESTS = 0x0004,
        
        /// <summary>
        ///  [8] Set this flag in order to receive the following ZDO request messages via the
        /// incomingMessageHandler callback: BINDING_TABLE_REQUEST, BIND_REQUEST, and
        /// UNBIND_REQUEST. If this configuration option is enabled, the stack will no longer send any
        /// ZDO response for these requests, and it is the application's responsibility to do so.
        /// </summary>
        EMBER_APP_HANDLES_ZDO_BINDING_REQUESTS = 0x0008,
    }
}
