//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Structure
{
    
    
    /// <summary>
    /// Class to implement the Ember Enumeration <b>EmberCounterType</b>
    /// </summary>
    public enum EmberCounterType
    {
        
        /// <summary>
        /// Default unknown value
        /// </summary>
        UNKNOWN = -1,
        
        /// <summary>
        ///  [0] The MAC received a broadcast
        /// </summary>
        EMBER_COUNTER_MAC_RX_BROADCAST = 0x0000,
        
        /// <summary>
        ///  [1] The MAC transmitted a broadcast
        /// </summary>
        EMBER_COUNTER_MAC_TX_BROADCAST = 0x0001,
        
        /// <summary>
        ///  [2] The MAC received a unicast
        /// </summary>
        EMBER_COUNTER_MAC_RX_UNICAST = 0x0002,
        
        /// <summary>
        ///  [3] The MAC successfully transmitted a unicast.
        /// </summary>
        EMBER_COUNTER_MAC_TX_UNICAST_SUCCESS = 0x0003,
        
        /// <summary>
        ///  [4] The MAC retried a unicast
        /// </summary>
        EMBER_COUNTER_MAC_TX_UNICAST_RETRY = 0x0004,
        
        /// <summary>
        ///  [5] The MAC unsuccessfully transmitted a unicast.
        /// </summary>
        EMBER_COUNTER_MAC_TX_UNICAST_FAILED = 0x0005,
        
        /// <summary>
        ///  [6] The APS layer received a data broadcast.
        /// </summary>
        EMBER_COUNTER_APS_DATA_RX_BROADCAST = 0x0006,
        
        /// <summary>
        ///  [7] The APS layer transmitted a data broadcast.
        /// </summary>
        EMBER_COUNTER_APS_DATA_TX_BROADCAST = 0x0007,
        
        /// <summary>
        ///  [8] The APS layer received a data unicast.
        /// </summary>
        EMBER_COUNTER_APS_DATA_RX_UNICAST = 0x0008,
        
        /// <summary>
        ///  [9] The APS layer successfully transmitted a data unicast.
        /// </summary>
        EMBER_COUNTER_APS_DATA_TX_UNICAST_SUCCESS = 0x0009,
        
        /// <summary>
        ///  [10] The APS layer retried a data unicast.
        /// </summary>
        EMBER_COUNTER_APS_DATA_TX_UNICAST_RETRY = 0x000A,
        
        /// <summary>
        ///  [11] The APS layer unsuccessfully transmitted a data unicast.
        /// </summary>
        EMBER_COUNTER_APS_DATA_TX_UNICAST_FAILED = 0x000B,
        
        /// <summary>
        ///  [12] The network layer successfully submitted a new route discovery to the MAC.
        /// </summary>
        EMBER_COUNTER_ROUTE_DISCOVERY_INITIATED = 0x000C,
        
        /// <summary>
        ///  [13] An entry was added to the neighbor table.
        /// </summary>
        EMBER_COUNTER_NEIGHBOR_ADDED = 0x000D,
        
        /// <summary>
        ///  [14] An entry was removed from the neighbor table.
        /// </summary>
        EMBER_COUNTER_NEIGHBOR_REMOVED = 0x000E,
        
        /// <summary>
        ///  [15] A neighbor table entry became stale because it had not been heard from.
        /// </summary>
        EMBER_COUNTER_NEIGHBOR_STALE = 0x000F,
        
        /// <summary>
        ///  [16] A node joined or rejoined to the network via this node.
        /// </summary>
        EMBER_COUNTER_JOIN_INDICATION = 0x0010,
        
        /// <summary>
        ///  [17] An entry was removed from the child table.
        /// </summary>
        EMBER_COUNTER_CHILD_REMOVED = 0x0011,
        
        /// <summary>
        ///  [18] EZSP-UART only. An overflow error occurred in the UART
        /// </summary>
        EMBER_COUNTER_ASH_OVERFLOW_ERROR = 0x0012,
        
        /// <summary>
        ///  [19] EZSP-UART only. A framing error occurred in the UART
        /// </summary>
        EMBER_COUNTER_ASH_FRAMING_ERROR = 0x0013,
        
        /// <summary>
        ///  [20] EZSP-UART only. An overrun error occurred in the UART
        /// </summary>
        EMBER_COUNTER_ASH_OVERRUN_ERROR = 0x0014,
        
        /// <summary>
        ///  [21] A message was dropped at the network layer because the NWK frame counter was not higher
        /// than the last message seen from that source.
        /// </summary>
        EMBER_COUNTER_NWK_FRAME_COUNTER_FAILURE = 0x0015,
        
        /// <summary>
        ///  [22] A message was dropped at the APS layer because the APS frame counter was not higher than
        /// the last message seen from that source.
        /// </summary>
        EMBER_COUNTER_APS_FRAME_COUNTER_FAILURE = 0x0016,
        
        /// <summary>
        ///  [23] Utility counter for general debugging use.
        /// </summary>
        EMBER_COUNTER_UTILITY = 0x0017,
        
        /// <summary>
        ///  [24] A message was dropped at the APS layer because it had APS encryption but the key
        /// associated with the sender has not been authenticated, and thus the key is not authorized for
        /// use in APS data messages.
        /// </summary>
        EMBER_COUNTER_APS_LINK_KEY_NOT_AUTHORIZED = 0x0018,
        
        /// <summary>
        ///  [25] A NWK encrypted message was received but dropped because decryption failed.
        /// </summary>
        EMBER_COUNTER_NWK_DECRYPTION_FAILURE = 0x0019,
        
        /// <summary>
        ///  [26] An APS encrypted message was received but dropped because decryption failed.
        /// </summary>
        EMBER_COUNTER_APS_DECRYPTION_FAILURE = 0x001A,
        
        /// <summary>
        ///  [27] The number of times we failed to allocate a set of linked packet buffers. This doesn't
        /// necessarily mean that the packet buffer count was 0 at the time, but that the number requested
        /// was greater than the number free.
        /// </summary>
        EMBER_COUNTER_ALLOCATE_PACKET_BUFFER_FAILURE = 0x001B,
        
        /// <summary>
        ///  [28] The number of relayed unicast packets.
        /// </summary>
        EMBER_COUNTER_RELAYED_UNICAST = 0x001C,
        
        /// <summary>
        ///  [29] The number of times we dropped a packet due to reaching the preset PHY to MAC queue limit
        /// (emMaxPhyToMacQueueLength). The limit will determine how many messages are accepted by
        /// the PHY between calls to emberTick(). After that limit is hit, packets will be dropped. The
        /// number of dropped packets will be recorded in this counter.
        ///     * <p>
        ///     * <b>Note:</b> For each call to
        /// emberCounterHandler() there may be more than 1 packet that was dropped due to the limit
        /// reached. The actual number of packets dropped will be returned in the 'data' parameter
        /// passed to that function.
        /// </summary>
        EMBER_COUNTER_PHY_TO_MAC_QUEUE_LIMIT_REACHED = 0x001D,
        
        /// <summary>
        ///  [30] The number of times we dropped a packet due to the packet-validate library checking a
        /// packet and rejecting it due to length or other formatting problems.
        /// </summary>
        EMBER_COUNTER_PACKET_VALIDATE_LIBRARY_DROPPED_COUNT = 0x001E,
        
        /// <summary>
        ///  [31] The number of times the NWK retry queue is full and a new message failed to be added. 
        /// </summary>
        EMBER_COUNTER_TYPE_NWK_RETRY_OVERFLOW = 0x001F,
        
        /// <summary>
        ///  [32] The number of times the PHY layer was unable to transmit due to a failed CCA
        /// </summary>
        EMBER_COUNTER_PHY_CCA_FAIL_COUNT = 0x0020,
        
        /// <summary>
        ///  [33] The number of times a NWK broadcast was dropped because the the broadcast table was full.
        /// </summary>
        EMBER_COUNTER_BROADCAST_TABLE_FULL = 0x0021,
        
        /// <summary>
        ///  [34] The number of low priority packet traffic arbitration requests.
        /// </summary>
        EMBER_COUNTER_PTA_LO_PRI_REQUESTED = 0x0022,
        
        /// <summary>
        ///  [35] The number of high priority packet traffic arbitration requests.
        /// </summary>
        EMBER_COUNTER_PTA_HI_PRI_REQUESTED = 0x0023,
        
        /// <summary>
        ///  [36] The number of low priority packet traffic arbitration requests denied.
        /// </summary>
        EMBER_COUNTER_PTA_LO_PRI_DENIED = 0x0024,
        
        /// <summary>
        ///  [37] The number of high priority packet traffic arbitration requests denied.
        /// </summary>
        EMBER_COUNTER_PTA_HI_PRI_DENIED = 0x0025,
        
        /// <summary>
        ///  [38] The number of aborted low priority packet traffic arbitration transmissions.
        /// </summary>
        EMBER_COUNTER_PTA_LO_PRI_TX_ABORTED = 0x0026,
        
        /// <summary>
        ///  [39] The number of aborted high priority packet traffic arbitration transmissions.
        /// </summary>
        EMBER_COUNTER_PTA_HI_PRI_TX_ABORTED = 0x0027,
        
        /// <summary>
        ///  [40] A placeholder giving the number of Ember counter types.
        /// </summary>
        EMBER_COUNTER_TYPE_COUNT = 0x0028,
    }
}
