//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Structure
{
    
    
    /// <summary>
    /// Class to implement the Ember Enumeration <b>EmberGpApplicationId</b>
    ///<p>
    /// Options to use when sending a message.
    ///</p> </summary>
    public enum EmberGpApplicationId
    {
        
        /// <summary>
        /// Default unknown value
        /// </summary>
        UNKNOWN = -1,
        
        /// <summary>
        ///  [0] Source identifier
        /// </summary>
        EMBER_GP_APPLICATION_SOURCE_ID = 0x0000,
        
        /// <summary>
        ///  [2] IEEE address
        /// </summary>
        EMBER_GP_APPLICATION_IEEE_ADDRESS = 0x0002,
    }
}
