//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Structure
{
    
    
    /// <summary>
    /// Class to implement the Ember Enumeration <b>EzspDecisionId</b>
    /// </summary>
    public enum EzspDecisionId
    {
        
        /// <summary>
        /// Default unknown value
        /// </summary>
        UNKNOWN = -1,
        
        /// <summary>
        ///  [0] Send the network key in the clear to all joining and rejoining devices.
        /// </summary>
        EZSP_ALLOW_JOINS = 0x0000,
        
        /// <summary>
        ///  [1] Send the network key encrypted with the joining or rejoining device's trust center link
        /// key. The trust center and any joining or rejoining device are assumed to share a link key,
        /// either preconfigured or obtained under a previous policy. This is the default value for the
        /// EZSP_TRUST_CENTER_POLICY.
        /// </summary>
        EZSP_ALLOW_PRECONFIGURED_KEY_JOINS = 0x0001,
        
        /// <summary>
        ///  [2] Send the network key encrypted with the rejoining device's trust center link key. The
        /// trust center and any rejoining device are assumed to share a link key, either preconfigured
        /// or obtained under a previous policy. No new devices are allowed to join.
        /// </summary>
        EZSP_ALLOW_REJOINS_ONLY = 0x0002,
        
        /// <summary>
        ///  [3] Reject all unsecured join and rejoin attempts.
        /// </summary>
        EZSP_DISALLOW_ALL_JOINS_AND_REJOINS = 0x0003,
        
        /// <summary>
        ///  [4] Send the network key in the clear to all joining devices. Rejoining devices are sent the
        /// network key encrypted with their trust center link key. The trust center and any rejoining
        /// device are assumed to share a link key, either preconfigured or obtained under a previous
        /// policy.
        /// </summary>
        EZSP_ALLOW_JOINS_REJOINS_HAVE_LINK_KEY = 0x0004,
        
        /// <summary>
        ///  [5] Take no action on trust center rejoin attempts.
        /// </summary>
        EZSP_IGNORE_TRUST_CENTER_REJOINS = 0x0005,
        
        /// <summary>
        ///  [6] Admit joins only if there is an entry in the transient key table. This corresponds to the
        /// Base Device Behavior specification where a Trust Center enforces all devices to join with an
        /// install code-derived link key.
        /// </summary>
        EZSP_BDB_JOIN_USES_INSTALL_CODE_KEY = 0x0006,
        
        /// <summary>
        ///  [7] Delay sending the network key to a new joining device.
        /// </summary>
        EZSP_DEFER_JOINS_REJOINS_HAVE_LINK_KEY = 0x0007,
        
        /// <summary>
        ///  [16] EZSP_BINDING_MODIFICATION_POLICY default decision. Do not allow the local binding
        /// table to be changed by remote nodes.
        /// </summary>
        EZSP_DISALLOW_BINDING_MODIFICATION = 0x0010,
        
        /// <summary>
        ///  [17] EZSP_BINDING_MODIFICATION_POLICY decision. Allow remote nodes to change the local
        /// binding table.
        /// </summary>
        EZSP_ALLOW_BINDING_MODIFICATION = 0x0011,
        
        /// <summary>
        ///  [18] EZSP_BINDING_MODIFICATION_POLICY decision. Allows remote nodes to set local
        /// binding entries only if the entries correspond to endpoints defined on the device, and for
        /// output clusters bound to those endpoints.
        /// </summary>
        EZSP_CHECK_BINDING_MODIFICATIONS_ARE_VALID_ENDPOINT_CLUSTERS = 0x0012,
        
        /// <summary>
        ///  [32] EZSP_UNICAST_REPLIES_POLICY default decision. The NCP will automatically send an
        /// empty reply (containing no payload) for every unicast received.
        /// </summary>
        EZSP_HOST_WILL_NOT_SUPPLY_REPLY = 0x0020,
        
        /// <summary>
        ///  [33] EZSP_UNICAST_REPLIES_POLICY decision. The NCP will only send a reply if it receives a
        /// sendReply command from the Host.
        /// </summary>
        EZSP_HOST_WILL_SUPPLY_REPLY = 0x0021,
        
        /// <summary>
        ///  [48] EZSP_POLL_HANDLER_POLICY default decision. Do not inform the Host when a child polls.
        /// </summary>
        EZSP_POLL_HANDLER_IGNORE = 0x0030,
        
        /// <summary>
        ///  [49] EZSP_POLL_HANDLER_POLICY decision. Generate a pollHandler callback when a child
        /// polls.
        /// </summary>
        EZSP_POLL_HANDLER_CALLBACK = 0x0031,
        
        /// <summary>
        ///  [64] EZSP_MESSAGE_CONTENTS_IN_CALLBACK_POLICY default decision. Include only the
        /// message tag in the messageSentHandler callback.
        /// </summary>
        EZSP_MESSAGE_TAG_ONLY_IN_CALLBACK = 0x0040,
        
        /// <summary>
        ///  [65] EZSP_MESSAGE_CONTENTS_IN_CALLBACK_POLICY decision. Include both the message tag
        /// and the message contents in the messageSentHandler callback.
        /// </summary>
        EZSP_MESSAGE_TAG_AND_CONTENTS_IN_CALLBACK = 0x0041,
        
        /// <summary>
        ///  [80] EZSP_TC_KEY_REQUEST_POLICY decision. When the Trust Center receives a request for a
        /// Trust Center link key, it will be ignored.
        /// </summary>
        EZSP_DENY_TC_KEY_REQUESTS = 0x0050,
        
        /// <summary>
        ///  [81] EZSP_TC_KEY_REQUEST_POLICY decision. When the Trust Center receives a request for a
        /// Trust Center link key, it will reply to it with the current key. If not key is currently in the
        /// key table for this device, a new key will be generated and sent to the device.
        /// </summary>
        EZSP_ALLOW_TC_KEY_REQUESTS_AND_SEND_CURRENT_KEY = 0x0051,
        
        /// <summary>
        ///  [82] EZSP_TC_KEY_REQUEST_POLICY decision. When the Trust Center receives a request for a
        /// Trust Center link key, it will generate a key to send to the joiner.
        /// </summary>
        EZSP_ALLOW_TC_KEY_REQUEST_AND_GENERATE_NEW_KEY = 0x0052,
        
        /// <summary>
        ///  [96] EZSP_APP_KEY_REQUEST_POLICY decision. When the Trust Center receives a request for
        /// an application link key, it will be ignored.
        /// </summary>
        EZSP_DENY_APP_KEY_REQUESTS = 0x0060,
        
        /// <summary>
        ///  [97] EZSP_APP_KEY_REQUEST_POLICY decision. When the Trust Center receives a request for
        /// an application link key, it will randomly generate a key and send it to both partners.
        /// </summary>
        EZSP_ALLOW_APP_KEY_REQUESTS = 0x0061,
        
        /// <summary>
        ///  [98] Indicates that packet validate library checks are enabled on the NCP.
        /// </summary>
        EZSP_PACKET_VALIDATE_LIBRARY_CHECKS_ENABLED = 0x0062,
        
        /// <summary>
        ///  [99] Indicates that packet validate library checks are NOT enabled on the NCP.
        /// </summary>
        EZSP_PACKET_VALIDATE_LIBRARY_CHECKS_DISABLED = 0x0063,
    }
}
