// License text here
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZigBeeNet.ZCL.Protocol;
using ZigBeeNet.ZCL.Field;
using ZigBeeNet.ZCL.Clusters.RSSILocation;

/**
 * Anchor Node Announce Command value object class.
 *
 * Cluster: RSSI Location. Command is sentTO the server.
 * This command is a specific command used for the RSSI Location cluster.
 *
 * Code is auto-generated. Modifications may be overwritten!
 */

/* Autogenerated: 14.02.2019 - 18:41 */
namespace ZigBeeNet.ZCL.Clusters.RSSILocation
{
   public class AnchorNodeAnnounceCommand : ZclCommand
   {
           /**
           * Anchor Node Address command message field.
           */
           public IeeeAddress AnchorNodeAddress { get; set; }

           /**
           * Coordinate 1 command message field.
           */
           public short Coordinate1 { get; set; }

           /**
           * Coordinate 2 command message field.
           */
           public short Coordinate2 { get; set; }

           /**
           * Coordinate 3 command message field.
           */
           public short Coordinate3 { get; set; }


           /**
           * Default constructor.
           */
           public AnchorNodeAnnounceCommand()
           {
               GenericCommand = false;
               ClusterId = 11;
               CommandId = 6;
               CommandDirection = ZclCommandDirection.CLIENT_TO_SERVER;
    }

    public override void Serialize(ZclFieldSerializer serializer)
    {
        serializer.Serialize(AnchorNodeAddress, ZclDataType.Get(DataType.IEEE_ADDRESS));
        serializer.Serialize(Coordinate1, ZclDataType.Get(DataType.SIGNED_16_BIT_INTEGER));
        serializer.Serialize(Coordinate2, ZclDataType.Get(DataType.SIGNED_16_BIT_INTEGER));
        serializer.Serialize(Coordinate3, ZclDataType.Get(DataType.SIGNED_16_BIT_INTEGER));
    }

    public override void Deserialize(ZclFieldDeserializer deserializer)
    {
        AnchorNodeAddress = deserializer.Deserialize<IeeeAddress>(ZclDataType.Get(DataType.IEEE_ADDRESS));
        Coordinate1 = deserializer.Deserialize<short>(ZclDataType.Get(DataType.SIGNED_16_BIT_INTEGER));
        Coordinate2 = deserializer.Deserialize<short>(ZclDataType.Get(DataType.SIGNED_16_BIT_INTEGER));
        Coordinate3 = deserializer.Deserialize<short>(ZclDataType.Get(DataType.SIGNED_16_BIT_INTEGER));
    }

       public override string ToString()
       {
           var builder = new StringBuilder();

           builder.Append("AnchorNodeAnnounceCommand [");
           builder.Append(base.ToString());
           builder.Append(", AnchorNodeAddress=");
           builder.Append(AnchorNodeAddress);
           builder.Append(", Coordinate1=");
           builder.Append(Coordinate1);
           builder.Append(", Coordinate2=");
           builder.Append(Coordinate2);
           builder.Append(", Coordinate3=");
           builder.Append(Coordinate3);
           builder.Append(']');

           return builder.ToString();
       }

   }
}
