// License text here
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZigBeeNet.ZCL.Protocol;
using ZigBeeNet.ZCL.Field;
using ZigBeeNet.ZCL.Clusters.General;

/**
 * Discover Commands Generated Response value object class.
 *
 * Cluster: General. Command is sentTO the server.
 * This command is a generic command used across the profile.
 *
 * The Discover Commands Generated Response is generated in response to a Discover Commands Generated * command. *
 * Code is auto-generated. Modifications may be overwritten!
 */

/* Autogenerated: 14.02.2019 - 18:41 */
namespace ZigBeeNet.ZCL.Clusters.General
{
   public class DiscoverCommandsGeneratedResponse : ZclCommand
   {
           /**
           * Discovery complete command message field.
           */
           public bool DiscoveryComplete { get; set; }

           /**
           * Command identifiers command message field.
           */
           public List<byte> CommandIdentifiers { get; set; }


           /**
           * Default constructor.
           */
           public DiscoverCommandsGeneratedResponse()
           {
               GenericCommand = true;
               CommandId = 20;
               CommandDirection = ZclCommandDirection.CLIENT_TO_SERVER;
    }

    public override void Serialize(ZclFieldSerializer serializer)
    {
        serializer.Serialize(DiscoveryComplete, ZclDataType.Get(DataType.BOOLEAN));
        serializer.Serialize(CommandIdentifiers, ZclDataType.Get(DataType.X_UNSIGNED_8_BIT_INTEGER));
    }

    public override void Deserialize(ZclFieldDeserializer deserializer)
    {
        DiscoveryComplete = deserializer.Deserialize<bool>(ZclDataType.Get(DataType.BOOLEAN));
        CommandIdentifiers = deserializer.Deserialize<List<byte>>(ZclDataType.Get(DataType.X_UNSIGNED_8_BIT_INTEGER));
    }

       public override string ToString()
       {
           var builder = new StringBuilder();

           builder.Append("DiscoverCommandsGeneratedResponse [");
           builder.Append(base.ToString());
           builder.Append(", DiscoveryComplete=");
           builder.Append(DiscoveryComplete);
           builder.Append(", CommandIdentifiers=");
           builder.Append(CommandIdentifiers);
           builder.Append(']');

           return builder.ToString();
       }

   }
}
