using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZigBeeNet.Security;
using ZigBeeNet.ZCL.Clusters.Price;
using ZigBeeNet.ZCL.Field;
using ZigBeeNet.ZCL.Protocol;


namespace ZigBeeNet.ZCL.Clusters.Price
{
    /// <summary>
    /// Get Tier Labels Command value object class.
    ///
    /// Cluster: Price. Command ID 0x0A is sent TO the server.
    /// This command is a specific command used for the Price cluster.
    ///
    /// This command allows a CLIENT to retrieve the tier labels associated with a given tariff;
    /// this command initiates a PublishTierLabels command from the server.
    ///
    /// Code is auto-generated. Modifications may be overwritten!
    /// </summary>
    public class GetTierLabelsCommand : ZclCommand
    {
        /// <summary>
        /// The cluster ID to which this command belongs.
        /// </summary>
        public const ushort CLUSTER_ID = 0x0700;

        /// <summary>
        /// The command ID.
        /// </summary>
        public const byte COMMAND_ID = 0x0A;

        /// <summary>
        /// Issuer Tariff ID command message field.
        /// 
        /// Unique identifier generated by the commodity supplier. This is used to identify
        /// the tariff that the labels apply to.
        /// </summary>
        public uint IssuerTariffId { get; set; }

        /// <summary>
        /// Default constructor.
        /// </summary>
        public GetTierLabelsCommand()
        {
            ClusterId = CLUSTER_ID;
            CommandId = COMMAND_ID;
            GenericCommand = false;
            CommandDirection = ZclCommandDirection.CLIENT_TO_SERVER;
        }

        internal override void Serialize(ZclFieldSerializer serializer)
        {
            serializer.Serialize(IssuerTariffId, ZclDataType.Get(DataType.UNSIGNED_32_BIT_INTEGER));
        }

        internal override void Deserialize(ZclFieldDeserializer deserializer)
        {
            IssuerTariffId = deserializer.Deserialize<uint>(ZclDataType.Get(DataType.UNSIGNED_32_BIT_INTEGER));
        }

        public override string ToString()
        {
            var builder = new StringBuilder();

            builder.Append("GetTierLabelsCommand [");
            builder.Append(base.ToString());
            builder.Append(", IssuerTariffId=");
            builder.Append(IssuerTariffId);
            builder.Append(']');

            return builder.ToString();
        }
    }
}
