//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " getBindingRemoteNodeId ".
    /// Returns the node ID for the binding's destination, if the ID is known. If a message is sent
    /// using the binding and the destination's ID is not known, the stack will discover the ID by
    /// broadcasting a ZDO address request. The application can avoid the need for this discovery by
    /// using setBindingRemoteNodeId when it knows the correct ID via some other means. The
    /// destination's node ID is forgotten when the binding is changed, when the local node reboots
    /// or, much more rarely, when the destination node changes its ID in response to an ID conflict.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspGetBindingRemoteNodeIdRequest : EzspFrameRequest
    {
        
        public const int FRAME_ID = 47;
        
        /// <summary>
        ///  The index of a binding table entry.
        /// </summary>
        private int _index;
        
        private EzspSerializer _serializer;
        
        public EzspGetBindingRemoteNodeIdRequest()
        {
            _frameId = FRAME_ID;
            _serializer = new EzspSerializer();
        }
        
        /// <summary>
        /// The index to set as <see cref="uint8_t"/> </summary>
        public void SetIndex(int index)
        {
            _index = index;
        }
        
        /// <summary>
        ///  The index of a binding table entry.
        /// Return the index as <see cref="System.Int32"/>
        /// </summary>
        public int GetIndex()
        {
            return _index;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public override int[] Serialize()
        {
            SerializeHeader(_serializer);
            _serializer.SerializeUInt8(_index);
            return _serializer.GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspGetBindingRemoteNodeIdRequest [index=");
            builder.Append(_index);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
