//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " setExtendedTimeout ".
    /// Tells the stack whether or not the normal interval between retransmissions of a retried
    /// unicast message should be increased by EMBER_INDIRECT_TRANSMISSION_TIMEOUT. The
    /// interval needs to be increased when sending to a sleepy node so that the message is not
    /// retransmitted until the destination has had time to wake up and poll its parent. The stack
    /// will automatically extend the timeout: - For our own sleepy children. - When an address
    /// response is received from a parent on behalf of its child. - When an indirect transaction
    /// expiry route error is received. - When an end device announcement is received from a sleepy
    /// node.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspSetExtendedTimeoutRequest : EzspFrameRequest
    {
        
        public const int FRAME_ID = 126;
        
        /// <summary>
        ///  The address of the node for which the timeout is to be set.
        /// </summary>
        private IeeeAddress _remoteEui64;
        
        /// <summary>
        ///  true if the retry interval should be increased by EMBER_INDIRECT_TRANSMISSION_TIMEOUT.
        /// false if the normal retry interval should be used.
        /// </summary>
        private bool _extendedTimeout;
        
        private EzspSerializer _serializer;
        
        public EzspSetExtendedTimeoutRequest()
        {
            _frameId = FRAME_ID;
            _serializer = new EzspSerializer();
        }
        
        /// <summary>
        /// The remoteEui64 to set as <see cref="EmberEUI64"/> </summary>
        public void SetRemoteEui64(IeeeAddress remoteEui64)
        {
            _remoteEui64 = remoteEui64;
        }
        
        /// <summary>
        /// The extendedTimeout to set as <see cref="bool"/> </summary>
        public void SetExtendedTimeout(bool extendedTimeout)
        {
            _extendedTimeout = extendedTimeout;
        }
        
        /// <summary>
        ///  The address of the node for which the timeout is to be set.
        /// Return the remoteEui64 as <see cref="IeeeAddress"/>
        /// </summary>
        public IeeeAddress GetRemoteEui64()
        {
            return _remoteEui64;
        }
        
        /// <summary>
        ///  true if the retry interval should be increased by EMBER_INDIRECT_TRANSMISSION_TIMEOUT.
        /// false if the normal retry interval should be used.
        /// Return the extendedTimeout as <see cref="System.Boolean"/>
        /// </summary>
        public bool GetExtendedTimeout()
        {
            return _extendedTimeout;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public override int[] Serialize()
        {
            SerializeHeader(_serializer);
            _serializer.SerializeEmberEui64(_remoteEui64);
            _serializer.SerializeBool(_extendedTimeout);
            return _serializer.GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspSetExtendedTimeoutRequest [remoteEui64=");
            builder.Append(_remoteEui64);
            builder.Append(", extendedTimeout=");
            builder.Append(_extendedTimeout);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
