//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " clearTemporaryDataMaybeStoreLinkKey ".
    /// Clears the temporary data associated with CBKE and the key establishment, most notably the
    /// ephemeral public/private key pair. If storeLinKey is true it moves the unverified link key
    /// stored in temporary storage into the link key table. Otherwise it discards the key.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspClearTemporaryDataMaybeStoreLinkKeyRequest : EzspFrameRequest
    {
        
        public const int FRAME_ID = 161;
        
        /// <summary>
        ///  A bool indicating whether to store (true) or discard (false) the unverified link key derived
        /// when ezspCalculateSmacs() was previously called.
        /// </summary>
        private bool _storeLinkKey;
        
        private EzspSerializer _serializer;
        
        public EzspClearTemporaryDataMaybeStoreLinkKeyRequest()
        {
            _frameId = FRAME_ID;
            _serializer = new EzspSerializer();
        }
        
        /// <summary>
        /// The storeLinkKey to set as <see cref="bool"/> </summary>
        public void SetStoreLinkKey(bool storeLinkKey)
        {
            _storeLinkKey = storeLinkKey;
        }
        
        /// <summary>
        ///  A bool indicating whether to store (true) or discard (false) the unverified link key derived
        /// when ezspCalculateSmacs() was previously called.
        /// Return the storeLinkKey as <see cref="System.Boolean"/>
        /// </summary>
        public bool GetStoreLinkKey()
        {
            return _storeLinkKey;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public override int[] Serialize()
        {
            SerializeHeader(_serializer);
            _serializer.SerializeBool(_storeLinkKey);
            return _serializer.GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspClearTemporaryDataMaybeStoreLinkKeyRequest [storeLinkKey=");
            builder.Append(_storeLinkKey);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
