//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    using ZigBeeNet.Hardware.Ember.Ezsp.Structure;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " getRouteTableEntry ".
    /// Returns the route table entry at the given index. The route table size can be obtained using
    /// the getConfigurationValue command.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspGetRouteTableEntryResponse : EzspFrameResponse
    {
        
        public const int FRAME_ID = 123;
        
        /// <summary>
        ///  EMBER_ERR_FATAL if the index is out of range or the device is an end device, and EMBER_SUCCESS
        /// otherwise.
        /// </summary>
        private EmberStatus _status;
        
        /// <summary>
        ///  The contents of the route table entry.
        /// </summary>
        private EmberRouteTableEntry _value;
        
        public EzspGetRouteTableEntryResponse(int[] inputBuffer) : 
                base(inputBuffer)
        {
            _status = deserializer.DeserializeEmberStatus();
            _value = deserializer.DeserializeEmberRouteTableEntry();
        }
        
        /// <summary>
        /// The status to set as <see cref="EmberStatus"/> </summary>
        public void SetStatus(EmberStatus status)
        {
            _status = status;
        }
        
        /// <summary>
        /// The value to set as <see cref="EmberRouteTableEntry"/> </summary>
        public void SetValue(EmberRouteTableEntry value)
        {
            _value = value;
        }
        
        /// <summary>
        ///  EMBER_ERR_FATAL if the index is out of range or the device is an end device, and EMBER_SUCCESS
        /// otherwise.
        /// Return the status as <see cref="EmberStatus"/>
        /// </summary>
        public EmberStatus GetStatus()
        {
            return _status;
        }
        
        /// <summary>
        ///  The contents of the route table entry.
        /// Return the value as <see cref="EmberRouteTableEntry"/>
        /// </summary>
        public EmberRouteTableEntry GetValue()
        {
            return _value;
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspGetRouteTableEntryResponse [status=");
            builder.Append(_status);
            builder.Append(", value=");
            builder.Append(_value);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
