//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " mfglibGetPower ".
    /// Returns the current radio power setting, as previously set via mfglibSetPower().
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspMfglibGetPowerResponse : EzspFrameResponse
    {
        
        public const int FRAME_ID = 141;
        
        /// <summary>
        ///  Power in units of dBm. Refer to radio data sheet for valid range.
        /// </summary>
        private int _power;
        
        public EzspMfglibGetPowerResponse(int[] inputBuffer) : 
                base(inputBuffer)
        {
            _power = deserializer.DeserializeInt8S();
        }
        
        /// <summary>
        /// The power to set as <see cref="int8s"/> </summary>
        public void SetPower(int power)
        {
            _power = power;
        }
        
        /// <summary>
        ///  Power in units of dBm. Refer to radio data sheet for valid range.
        /// Return the power as <see cref="System.Int32"/>
        /// </summary>
        public int GetPower()
        {
            return _power;
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspMfglibGetPowerResponse [power=");
            builder.Append(_power);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
