//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    using ZigBeeNet.Hardware.Ember.Ezsp.Structure;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " calculateSmacs283k1 ".
    /// Calculates the SMAC verification keys for both the initiator and responder roles of CBKE for
    /// the 283k1 ECC curve using the passed parameters and the stored public/private key pair
    /// previously generated with ezspGenerateKeysRetrieveCert283k1(). It also stores the
    /// unverified link key data in temporary storage on the NCP until the key establishment is
    /// complete.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspCalculateSmacs283k1Response : EzspFrameResponse
    {
        
        public const int FRAME_ID = 234;
        
        /// <summary>
        ///  The result of the CBKE operation.
        /// </summary>
        private EmberStatus _status;
        
        public EzspCalculateSmacs283k1Response(int[] inputBuffer) : 
                base(inputBuffer)
        {
            _status = deserializer.DeserializeEmberStatus();
        }
        
        /// <summary>
        /// The status to set as <see cref="EmberStatus"/> </summary>
        public void SetStatus(EmberStatus status)
        {
            _status = status;
        }
        
        /// <summary>
        ///  The result of the CBKE operation.
        /// Return the status as <see cref="EmberStatus"/>
        /// </summary>
        public EmberStatus GetStatus()
        {
            return _status;
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspCalculateSmacs283k1Response [status=");
            builder.Append(_status);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
