//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " gpSinkTableRemoveEntry ".
    /// Removes the sink table entry stored at the passed index.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspGpSinkTableRemoveEntryRequest : EzspFrameRequest
    {
        
        public const int FRAME_ID = 224;
        
        /// <summary>
        ///  The index of the requested sink entry.
        /// </summary>
        private int _sinkIndex;
        
        private EzspSerializer _serializer;
        
        public EzspGpSinkTableRemoveEntryRequest()
        {
            _frameId = FRAME_ID;
            _serializer = new EzspSerializer();
        }
        
        /// <summary>
        /// The sinkIndex to set as <see cref="uint8_t"/> </summary>
        public void SetSinkIndex(int sinkIndex)
        {
            _sinkIndex = sinkIndex;
        }
        
        /// <summary>
        ///  The index of the requested sink entry.
        /// Return the sinkIndex as <see cref="System.Int32"/>
        /// </summary>
        public int GetSinkIndex()
        {
            return _sinkIndex;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public override int[] Serialize()
        {
            SerializeHeader(_serializer);
            _serializer.SerializeUInt8(_sinkIndex);
            return _serializer.GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspGpSinkTableRemoveEntryRequest [sinkIndex=");
            builder.Append(_sinkIndex);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
