//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    using ZigBeeNet.Hardware.Ember.Ezsp.Structure;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " getNeighbor ".
    /// Returns the neighbor table entry at the given index. The number of active neighbors can be
    /// obtained using the neighborCount command.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspGetNeighborResponse : EzspFrameResponse
    {
        
        public const int FRAME_ID = 121;
        
        /// <summary>
        ///  EMBER_ERR_FATAL if the index is greater or equal to the number of active neighbors, or if the
        /// device is an end device. Returns EMBER_SUCCESS otherwise.
        /// </summary>
        private EmberStatus _status;
        
        /// <summary>
        ///  The contents of the neighbor table entry.
        /// </summary>
        private EmberNeighborTableEntry _value;
        
        public EzspGetNeighborResponse(int[] inputBuffer) : 
                base(inputBuffer)
        {
            _status = deserializer.DeserializeEmberStatus();
            _value = deserializer.DeserializeEmberNeighborTableEntry();
        }
        
        /// <summary>
        /// The status to set as <see cref="EmberStatus"/> </summary>
        public void SetStatus(EmberStatus status)
        {
            _status = status;
        }
        
        /// <summary>
        /// The value to set as <see cref="EmberNeighborTableEntry"/> </summary>
        public void SetValue(EmberNeighborTableEntry value)
        {
            _value = value;
        }
        
        /// <summary>
        ///  EMBER_ERR_FATAL if the index is greater or equal to the number of active neighbors, or if the
        /// device is an end device. Returns EMBER_SUCCESS otherwise.
        /// Return the status as <see cref="EmberStatus"/>
        /// </summary>
        public EmberStatus GetStatus()
        {
            return _status;
        }
        
        /// <summary>
        ///  The contents of the neighbor table entry.
        /// Return the value as <see cref="EmberNeighborTableEntry"/>
        /// </summary>
        public EmberNeighborTableEntry GetValue()
        {
            return _value;
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspGetNeighborResponse [status=");
            builder.Append(_status);
            builder.Append(", value=");
            builder.Append(_value);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
