//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    using ZigBeeNet.Hardware.Ember.Ezsp.Structure;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " lookupEui64ByNodeId ".
    /// Returns the EUI64 that corresponds to the specified node ID. The EUI64 is found by searching
    /// through all stack tables for the specified node ID.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspLookupEui64ByNodeIdResponse : EzspFrameResponse
    {
        
        public const int FRAME_ID = 97;
        
        /// <summary>
        ///  EMBER_SUCCESS if the EUI64 was found, EMBER_ERR_FATAL if the EUI64 is not known.
        /// </summary>
        private EmberStatus _status;
        
        /// <summary>
        ///  The EUI64 of the node to look up.
        /// </summary>
        private IeeeAddress _eui64;
        
        public EzspLookupEui64ByNodeIdResponse(int[] inputBuffer) : 
                base(inputBuffer)
        {
            _status = deserializer.DeserializeEmberStatus();
            _eui64 = deserializer.DeserializeEmberEui64();
        }
        
        /// <summary>
        /// The status to set as <see cref="EmberStatus"/> </summary>
        public void SetStatus(EmberStatus status)
        {
            _status = status;
        }
        
        /// <summary>
        /// The eui64 to set as <see cref="EmberEUI64"/> </summary>
        public void SetEui64(IeeeAddress eui64)
        {
            _eui64 = eui64;
        }
        
        /// <summary>
        ///  EMBER_SUCCESS if the EUI64 was found, EMBER_ERR_FATAL if the EUI64 is not known.
        /// Return the status as <see cref="EmberStatus"/>
        /// </summary>
        public EmberStatus GetStatus()
        {
            return _status;
        }
        
        /// <summary>
        ///  The EUI64 of the node to look up.
        /// Return the eui64 as <see cref="IeeeAddress"/>
        /// </summary>
        public IeeeAddress GetEui64()
        {
            return _eui64;
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspLookupEui64ByNodeIdResponse [status=");
            builder.Append(_status);
            builder.Append(", eui64=");
            builder.Append(_eui64);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
