//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    using ZigBeeNet.Hardware.Ember.Ezsp.Structure;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " setPreinstalledCbkeData283k1 ".
    /// Sets the device's 283k1 curve CA public key, local certificate, and static private key on the
    /// NCP associated with this node. The associated data needs to be set via the setValue method
    /// before calling this method.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspSetPreinstalledCbkeData283k1Response : EzspFrameResponse
    {
        
        public const int FRAME_ID = 237;
        
        /// <summary>
        ///  The result of the CBKE operation.
        /// </summary>
        private EmberStatus _status;
        
        public EzspSetPreinstalledCbkeData283k1Response(int[] inputBuffer) : 
                base(inputBuffer)
        {
            _status = deserializer.DeserializeEmberStatus();
        }
        
        /// <summary>
        /// The status to set as <see cref="EmberStatus"/> </summary>
        public void SetStatus(EmberStatus status)
        {
            _status = status;
        }
        
        /// <summary>
        ///  The result of the CBKE operation.
        /// Return the status as <see cref="EmberStatus"/>
        /// </summary>
        public EmberStatus GetStatus()
        {
            return _status;
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspSetPreinstalledCbkeData283k1Response [status=");
            builder.Append(_status);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
