//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    using ZigBeeNet.Hardware.Ember.Ezsp.Structure;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " invalidCommand ".
    /// Indicates that the NCP received an invalid command.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspInvalidCommandResponse : EzspFrameResponse
    {
        
        public const int FRAME_ID = 88;
        
        /// <summary>
        ///  The reason why the command was invalid.
        /// </summary>
        private EzspStatus _reason;
        
        public EzspInvalidCommandResponse(int[] inputBuffer) : 
                base(inputBuffer)
        {
            _reason = deserializer.DeserializeEzspStatus();
        }
        
        /// <summary>
        /// The reason to set as <see cref="EzspStatus"/> </summary>
        public void SetReason(EzspStatus reason)
        {
            _reason = reason;
        }
        
        /// <summary>
        ///  The reason why the command was invalid.
        /// Return the reason as <see cref="EzspStatus"/>
        /// </summary>
        public EzspStatus GetReason()
        {
            return _reason;
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspInvalidCommandResponse [reason=");
            builder.Append(_reason);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
