//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " lookupNodeIdByEui64 ".
    /// Returns the node ID that corresponds to the specified EUI64. The node ID is found by searching
    /// through all stack tables for the specified EUI64.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspLookupNodeIdByEui64Request : EzspFrameRequest
    {
        
        public const int FRAME_ID = 96;
        
        /// <summary>
        ///  The EUI64 of the node to look up.
        /// </summary>
        private IeeeAddress _eui64;
        
        private EzspSerializer _serializer;
        
        public EzspLookupNodeIdByEui64Request()
        {
            _frameId = FRAME_ID;
            _serializer = new EzspSerializer();
        }
        
        /// <summary>
        /// The eui64 to set as <see cref="EmberEUI64"/> </summary>
        public void SetEui64(IeeeAddress eui64)
        {
            _eui64 = eui64;
        }
        
        /// <summary>
        ///  The EUI64 of the node to look up.
        /// Return the eui64 as <see cref="IeeeAddress"/>
        /// </summary>
        public IeeeAddress GetEui64()
        {
            return _eui64;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public override int[] Serialize()
        {
            SerializeHeader(_serializer);
            _serializer.SerializeEmberEui64(_eui64);
            return _serializer.GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspLookupNodeIdByEui64Request [eui64=");
            builder.Append(_eui64);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
