//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBeeNet.Hardware.Ember.Ezsp.Command
{
    using ZigBeeNet.Hardware.Ember.Internal.Serializer;
    using ZigBeeNet.Hardware.Ember.Ezsp.Structure;
    
    
    /// <summary>
    /// Class to implement the Ember EZSP command " setBinding ".
    /// Sets an entry in the binding table.
    /// This class provides methods for processing EZSP commands.
    /// </summary>
    public class EzspSetBindingRequest : EzspFrameRequest
    {
        
        public const int FRAME_ID = 43;
        
        /// <summary>
        ///  The index of a binding table entry.
        /// </summary>
        private int _index;
        
        /// <summary>
        ///  The contents of the binding entry.
        /// </summary>
        private EmberBindingTableEntry _value;
        
        private EzspSerializer _serializer;
        
        public EzspSetBindingRequest()
        {
            _frameId = FRAME_ID;
            _serializer = new EzspSerializer();
        }
        
        /// <summary>
        /// The index to set as <see cref="uint8_t"/> </summary>
        public void SetIndex(int index)
        {
            _index = index;
        }
        
        /// <summary>
        /// The value to set as <see cref="EmberBindingTableEntry"/> </summary>
        public void SetValue(EmberBindingTableEntry value)
        {
            _value = value;
        }
        
        /// <summary>
        ///  The index of a binding table entry.
        /// Return the index as <see cref="System.Int32"/>
        /// </summary>
        public int GetIndex()
        {
            return _index;
        }
        
        /// <summary>
        ///  The contents of the binding entry.
        /// Return the value as <see cref="EmberBindingTableEntry"/>
        /// </summary>
        public EmberBindingTableEntry GetValue()
        {
            return _value;
        }
        
        /// <summary>
        /// Method for serializing the command fields </summary>
        public override int[] Serialize()
        {
            SerializeHeader(_serializer);
            _serializer.SerializeUInt8(_index);
            _serializer.SerializeEmberBindingTableEntry(_value);
            return _serializer.GetPayload();
        }
        
        public override string ToString()
        {
            System.Text.StringBuilder builder = new System.Text.StringBuilder();
            builder.Append("EzspSetBindingRequest [index=");
            builder.Append(_index);
            builder.Append(", value=");
            builder.Append(_value);
            builder.Append(']');
            return builder.ToString();
        }
    }
}
