using System;
using System.Collections.Generic;
using System.Text;

namespace ZigBeeNet.Hardware.TI.CC2531.Packet.SimpleAPI
{
    public class ZB_APP_REGISTER_REQUEST : ZToolPacket
    {
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.AppEndPoint</name>
        /// <summary>The endpoint of the device on which this application should reside ( value 1 through 240 ). This should
        /// be set to same value for all devices in this network. </summary>
        public byte AppEndPoint { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.AppProfileID</name>
        /// <summary>The profile id of the application. This should be set to same value for all devices in this
        /// network.</summary>
        public DoubleByte AppProfileID { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.DeviceId</name>
        /// <summary>The device description id for this endpoint</summary>
        public DoubleByte DeviceId { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.DeviceVersion</name>
        /// <summary>The version of the device description</summary>
        public byte DeviceVersion { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.InputCommandsList</name>
        /// <summary>List of input commands that are processed by this device application</summary>
        public DoubleByte[] InputCommandsList { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.InputCommandsNum</name>
        /// <summary>The number of Input commands Ids following in the InputCommandsList</summary>
        public byte InputCommandsNum { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.OutputCommandsList</name>
        /// <summary>List of output commands that are generated by this device application</summary>
        public DoubleByte[] OutputCommandsList { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.OutputCommandsNum</name>
        /// <summary>The number of Output command Ids in the OutputCommandsList</summary>
        public byte OutputCommandsNum { get; set; }
        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST.Unused</name>
        /// <summary>Unused parameter</summary>
        public byte Unused { get; set; }

        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST</name>
        /// <summary>Constructor</summary>
        public ZB_APP_REGISTER_REQUEST()
        {
            this.InputCommandsList = new DoubleByte[0xff];
            this.OutputCommandsList = new DoubleByte[0xff];
        }

        /// <name>TI.ZPI2.ZB_APP_REGISTER_REQUEST</name>
        /// <summary>Constructor</summary>
        public ZB_APP_REGISTER_REQUEST(byte num1, DoubleByte num2, DoubleByte num3, byte num4, byte num5, byte num6,
                DoubleByte[] numArray1, byte num7, DoubleByte[] numArray2)
        {
            this.AppEndPoint = num1;
            this.AppProfileID = num2;
            this.DeviceId = num3;
            this.DeviceVersion = num4;
            this.Unused = num5;
            this.InputCommandsNum = num6;
            this.InputCommandsList = new DoubleByte[numArray1.Length];
            this.InputCommandsList = numArray1;

            this.OutputCommandsNum = num7;
            this.OutputCommandsList = new DoubleByte[numArray2.Length];
            this.OutputCommandsList = numArray2;

            byte[] framedata = new byte[9 + this.InputCommandsList.Length * 2 + this.OutputCommandsList.Length * 2];
            framedata[0] = this.AppEndPoint;
            framedata[1] = this.AppProfileID.Lsb;
            framedata[2] = this.AppProfileID.Msb;
            framedata[3] = this.DeviceId.Lsb;
            framedata[4] = this.DeviceId.Msb;
            framedata[5] = this.DeviceVersion;
            framedata[6] = this.Unused;
            framedata[7] = this.InputCommandsNum;
            for (int i = 0; i < this.InputCommandsList.Length; i++)
            {
                framedata[(i * 2) + 8] = this.InputCommandsList[i].Lsb;
                framedata[(i * 2) + 9] = this.InputCommandsList[i].Msb;
            }
            framedata[((this.InputCommandsList.Length) * 2) + 8] = this.OutputCommandsNum;
            for (int i = 0; i < this.OutputCommandsList.Length; i++)
            {
                framedata[(i * 2) + ((this.InputCommandsList.Length) * 2) + 9] = this.OutputCommandsList[i].Lsb;
                framedata[(i * 2) + ((this.InputCommandsList.Length) * 2) + 10] = this.OutputCommandsList[i].Msb;
            }
            BuildPacket(new DoubleByte((ushort)ZToolCMD.ZB_APP_REGISTER_REQUEST), framedata);

        }
    }
}
